import { Controller, Get } from '@nestjs/common';  // Import decorators from NestJS
import { ProblemService } from './problem.service';  // Import the service we created earlier
import { Problem } from '@prisma/client';  // Import the Problem type generated by Prisma

@Controller('problems')  // This decorator defines the route for this controller
export class ProblemController {
  constructor(private readonly problemService: ProblemService) {}  // Inject the ProblemService

  @Get()  // This decorator defines a GET HTTP route at /problems
  async getAllProblems(): Promise<Problem[]> {
    return this.problemService.getAllProblems();  // Call the service method to fetch problems
  }
}
