import { Injectable } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';  // Prisma service for interacting with the DB
import { Problem } from '@prisma/client';  // The type for Problem (auto-generated by Prisma)

@Injectable()  // This decorator marks the class as a provider (a service) that can be injected into other classes
export class ProblemService {
  constructor(private prisma: PrismaService) {}  // Inject PrismaService into the constructor

  // Method to fetch all problems
  async getAllProblems(): Promise<Problem[]> {
    return this.prisma.problem.findMany();  // Using Prisma to fetch all problems from DB
  }
}
