import { Controller, Get, Body, Post } from '@nestjs/common';  // Import decorators from NestJS
import { ProblemService } from './problem.service';  // Import the service we created earlier
import { Problem } from '@prisma/client';  // Import the Problem type generated by Prisma
import { CreateProblemDto } from './dto/create-problem.dto';  // Import the DTO for creating a problem

@Controller('problems')  // This decorator defines the route for this controller
export class ProblemController {
  constructor(private readonly problemService: ProblemService) {}  // Inject the ProblemService

  @Get()  // This decorator defines a GET HTTP route at /problems
  async getAllProblems(): Promise<Problem[]> {
    return this.problemService.getAllProblems();  // Call the service method to fetch problems
  }

  @Post()  // This decorator defines a POST HTTP route at /problems
  create(@Body() createProblemDto: CreateProblemDto){
    return this.problemService.create(createProblemDto);
  }
}
