name: CI Workflow

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch
  pull_request:
    branches:
      - dev  # Trigger on PR to dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Adjust Node.js version if necessary

      - name: Install dependencies (in frontend directory)
        run: |
          cd frontend  # Change to frontend directory
          npm install
          npm ci  # This ensures the exact dependency versions are installed

      - name: Run tests
        run: |
          cd frontend  # Ensure you're in the frontend directory
          npm run test || true  # Running tests, ignore failures for now (or handle as needed)

      - name: Build the project
        run: |
          cd frontend  # Change to frontend directory
          npm run build

      - name: Deploy (if needed)
        run: |
          # Deploy command here if you want to trigger deployment
